version: 2.1

jobs:
  linting:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
            pip install pylint
      - run:
          name: run lint
          command: |
            ./hadolint Dockerfile
            pylint --disable=R,C,W1203,W1202,W0613 app.py
  build_and_deploy_docker_app:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker
          command: |
            docker build -t udacity-capstone .
      - run:
          name: push docker
          command: |
            dockerpath="${DOCKERHUB_USER}/udacity-capstone"
            docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}
            docker tag udacity-capstone ${DOCKERHUB_USER}/udacity-capstone:latest
            docker push ${DOCKERHUB_USER}/udacity-capstone:latest

workflows:
  default:
    jobs:
      - linting
