version: 2.1

jobs:
  linting:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
      - run:
          name: run lint
          command: |
            ./hadolint Dockerfile
            pylint --disable=R,C,W1203,W1202 app.py

workflows:
  default:
    jobs:
      - linting